### ISSUE TITLE
Error when sending to Kindle

### ISSUE THREAD

**Issue by bobsys** [postlight/parser#539]
Worked great for a few months and this week when I clicked "Send to Kindle" I got a message "Error Sending" in red. This happenes with any web page I tried and on other computers. I verified that my setup on Amazon was correct and that the Kindle email address is correct. Did something change at Amazon?

- **Platform**: Windows 10 64 bit
- **Mercury Parser Version**: 4.3.1
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**: 80.0.3987.122 (Official Build) (64-bit)

## Expected Behavior

The page should be sent to Kindle

## Current Behavior

An error is generated and nothing is sent

## Steps to Reproduce

Described below

## Detailed Description

Worked great for a few months and this week when I clicked "Send to Kindle" I got a message "Error Sending" in red. This happenes with any web page I tried and on other computers. I verified that my setup on Amazon was correct and that the Kindle email address is correct. Did something change at Amazon?

**Comment by Rabolimbo** [comment]
I have the same issue. MacOS 10.15.3. Error message on every page I try to send to Kindle. All Kindle settings are accurate. This was a sudden change that started a few days ago.

**Comment by FBoucher** [comment]
Same issue. It looks related to certificate... ??

**Comment by radiaccio** [comment]
I have the same issue: "_error sending_". It started to happen this week.

**Comment by zhouyifan0904** [comment]
Same issue. Console displays this message upon sending. Seems like an expired certificate.
![image](https://user-images.githubusercontent.com/13145408/76114901-f26caf00-5f9b-11ea-82dd-fc0208c14545.png)

**Comment by bobsys** [comment]
So this looks like a simple fix.
Is anyone home to correct this problem?

**Comment by FBoucher** [comment]
I contacted them not sure if it's related... but it looks fixed now.

**Comment by Rabolimbo** [comment]
It works!

**Comment by radiaccio** [comment]
It works for me too!

**Comment by bobsys** [comment]
Yes it works for me as well.
Was this due to a change by the devs or was it something done at Amazon?

**Comment by ciprian-cimpan** [comment]
I get a different error message, CORS related:

```Access to fetch at 'https://mercury-kindlegen.postlight.com/send-to-kindle' from origin 'chrome-extension://XXX' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.```

Any ideas on how to bypass that?

**Comment by nosarthur** [comment]
I just installed Mercury reader and filled in the kindle information. But cannot send to kindle, clicking that button shows 'error sending'

**Comment by FBoucher** [comment]
Yes sending to Kindle looks broken again, last successful transfer was Jan 17 for me.

It look like it's may be Amazon who changed something in there API because other services like Klip.me also stop working. 

The only work around right now is to use the "official" Send To Kindle extension or the use the email.

**Comment by MartinPee** [comment]
Yes, sending to Kindle is broken again. Thats pity. One of the most usefull extentions. Is there anything being done upon this issue?

**Comment by mcorrello** [comment]
I'm able to successfully get it to send to Kindle. It took a few minutes to show up on my device and I had to make sure Postlight reader had the correct email for the device I wanted.

Is anyone still seeing this issue?

**Comment by FBoucher** [comment]
This has been fixed for a while now.

**Comment by mcorrello** [comment]
Issue has been resolved
