### ISSUE TITLE
Drop Cap Characters Missing when Parsed

### ISSUE THREAD

**Issue by michaelkirkpatrick** [postlight/parser#555]
- **Platform**: Mercury Reader
- **Mercury Reader Version**: 4.3.1.0
- **Browser Version (if a browser bug)**: Chrome 81.0.4044.122 (macOS)

## Expected Behavior

When loading Mercury Reader for an article, drop cap characters are included in the parsed page.

## Current Behavior

When loading Mercury Reader for an article, characters rendered in drop cap are omitted.

## Steps to Reproduce

1. Load this [Medium article](https://medium.com/@ASlavitt/the-three-most-likely-scenarios-to-defeat-the-coronavirus-5a63ac30aec8) in Chrome
2. Note that in the opening paragraph the letter "T" is in drop cap and the sentence reads "The calls started early today"

<img width="1230" alt="Screen Shot 2020-04-27 at 11 02 15 AM" src="https://user-images.githubusercontent.com/23110714/80405811-f91af280-8877-11ea-87ec-9c4c375eccf2.png">

3. When using the Mercury Reader extension, the drop cap "T" is omitted.

<img width="1230" alt="Screen Shot 2020-04-27 at 11 02 07 AM" src="https://user-images.githubusercontent.com/23110714/80405829-ff10d380-8877-11ea-9c41-e65b74cfe088.png">

## Detailed Description

The HTML on the page is as follows for that portion: `<p id="7a70" class="if is ap ce ih b eq ii it es ij iu ik il fd im in fe io ip ff iq ir dq" data-selectable-paragraph=""><span class="r iv iw ix iy iz ja jb jc jd da">T</span>he calls started early today...</p>`. My hypothesis is that Reader View is omitting text within a `<span>` element at the start of a `<p>`.

**Comment by johnholdun** [comment]
Fixed by #696
