### ISSUE TITLE
Date showing a value which is not found on webpage

### ISSUE THREAD

**Issue by RobLockhart** [postlight/parser#637]
- **Platform**: Windows 11, build 22000.348
- **Mercury Parser Version**: 4.3.1.0
- **Browser Version (if a browser bug)**: Brave 1.32.113 Chromium 96.0.4664.45 official build 64-bit

## Expected Behavior

It should show the correct date of the article. For some reason, it shows date Jan 19, 1970. No where on that page is that date used or shown.

## Current Behavior

What happens right now is it shows the date of Jan 19, 1970

## Steps to Reproduce

First install Mercury Parser. Then open this page:
https://www.msn.com/en-us/news/world/merkel-to-enforce-lockdown-for-unvaccinated-with-covid-surging/ar-AARnIC0

Then click the Mercury link. You will see that date below the title. NOTE that the entire article seems to be shown correctly and in-tact. The date should be shown as "Yesterday" or 12/2/2021 (equivalent of "Yesterday").

![Mercury-enabled-wrong-date](https://user-images.githubusercontent.com/34723222/144697143-2e4de8c6-8712-4d8b-ac40-f8fe6db2b90b.png)
![Mercury-not-enabled-correct-date](https://user-images.githubusercontent.com/34723222/144697144-e53ce8d9-3b39-4dfe-a8fc-b3895d01ea3b.png)

**Comment by austinmbrown** [comment]
This should be fixed now.
