### ISSUE TITLE
"Send To Kindle" format needs to change to EPUB by August 2022

### ISSUE THREAD

**Issue by bobsys** [postlight/parser#669]
- **All**:
- **Mercury Parser Version**:
- **Node Version (if a Node bug)**:
- **Browser Version (if a browser bug)**:

## Expected Behavior
"Send To Kindle" uses correct document format.

Amazon will no longer support the MOBI format after August 2022. Documents sent to the system will need to be in EPUB format.

## Current Behavior

"Send To Kindle" function should send documents in EPUB format instead of the current format.

**Comment by johnholdun** [comment]
Thanks for bringing this up! We'll make sure this gets done before the deadline.

**Comment by bobsys** [comment]
That's great!
Will an update be pushed? Or do clients have to look for it?

**Comment by johnholdun** [comment]
Users of the Chrome extension should get this updated functionality automatically when it ships. Thanks for offering to test! We'll reach out if we could use the extra help 🎉

**Comment by bobsys** [comment]
Has this update been released? 
I am getting notices from Amazon when I send to Kindle that MOBI will no longer be supported.

**Comment by johnholdun** [comment]
Not yet! We are QAing internally and things are looking good, though, so it should be coming soon. Do those notices have a specific date for when MOBI support will end? I haven't been able to find anything concrete.

**Comment by bobsys** [comment]
Here is the message I am getting (not very clear):

Dear Kindle Customer,

Thank you for using the Send to Kindle service to send personal documents to your Kindle library. We noticed that the following document(s), sent by you at 05:44 PM on Wed, Aug 17, 2022 GMT are in MOBI (.mobi, .azw) formats:  
* 1660758258956.mobi


We wanted to let you know that starting August 2022, you’ll no longer be able to send MOBI (.mobi, .azw) files to your Kindle library. Any MOBI files already in your library will not be affected by this change. MOBI is an older file format and won’t support the newest Kindle features for documents. Any existing MOBI files you want to read with our most up-to-date features for documents will need to be re-sent in a compatible format.

We wanted to let you know that starting August 2022, you’ll no longer be able to send MOBI (.mobi, .azw) files to your Kindle library. Any MOBI files already in your library will not be affected by this change. MOBI is an older file format and won’t support the newest Kindle features for documents. Any existing MOBI files you want to read with our most up-to-date features for documents will need to be re-sent in a compatible format.

Compatible formats now include EPUB (.epub), which you can send to your library using your Send to Kindle email address. We’ll also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac. 

 If you have any questions, please visit our help page or contact our Customer Service team.

**Comment by johnholdun** [comment]
Hi again, just checking in to say that we have this complete and results are looking good—better than the old MOBI results, even. It should ship in the next week or so, pending some final deploy details.

**Comment by bobsys** [comment]
Thanks.
How will I know that I am using the new version?

**Comment by johnholdun** [comment]
We've submitted a new version of the extension that generates ePub files to the Chrome web store and expect it to be published in the next day or so! You should recognize a difference in formatting, especially with regards to images. Let us know what you think of the changes, and thanks so much for your patience!

**Comment by FBoucher** [comment]
This should be close the extension now send epub.... The title is only numbers... put it's an epub

**Comment by johnholdun** [comment]
True, thank you!
