### ISSUE TITLE
yarn add @postlight/parser fails (wrong package name in README?)

### ISSUE THREAD

**Issue by fungilation** [postlight/parser#690]
## Expected Behavior

yarn add <this package> should work.

## Current Behavior

README has

```
yarn add @postlight/parser
```

Running that results in
```
yarn add @postlight/parser 
yarn add v1.22.19
[1/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@postlight%2fparser: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/gfung/Documents/code/WonderSwipe/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command
```

## Steps to Reproduce

`yarn add @postlight/parser`

## Detailed Description

Is package @postlight/parser, or @postlight/mercury-parser? It's been the latter for a long while.

Also, latest version is 2.2.2 on github, but that's not on npm yet (latest on npm is 2.2.1)

**Comment by TonyRL** [comment]
Starting with 2.2.2 it's called `@postlight/parser` as it's rebranded in https://github.com/postlight/parser/pull/688.
[@postlight/parser](https://www.npmjs.com/package/@postlight/parser) is available on npm now.
