### ISSUE TITLE
Mercury Reader doesn't keep web links formatting when printing to PDF from browser print

### ISSUE THREAD

**Issue by Epicene** [postlight/parser#691]
## Expected Behavior

When displaying (parsing) a web page with Mercury Reader, the page preview in Mercury Reader shows web links with their formatting (color, underline).

From the Mercury Reader preview, when calling the browser print function (CTRL + P or Cmd + P) to print to PDF, link formatting should be kept.

For instance, another similar extension Just Read, can keep web links formatting when printing in PDF.

## Current Behavior

From the Mercury Reader preview, when calling the browser print function (CTRL + P or Cmd + P) to print to PDF, link formatting is completely lost.

When opening the PDF produced, links are there when you hover them with the mouse cursor. But you can't see them! You have to search them thus! 

Tested on macOS 10.14.6 Mojave, 10.15 Catalina and Windows 10 21H2.

## Steps to Reproduce

1. Display a web page with web links (colored, undelined).
2. Call Mercury Reader. You can see the links.
3. Print the document produced by Mercury Reader (CTRL + P or Cmd + P)
4. In the print preview pane, no more links are shown. They have lost their formatting.

## Possible Solution

Just Read succeeds in keeping web links formatting when printing the document in PDF. Mercury Reader should do it too!

**Comment by jtx007** [comment]
This issue is being addressed by the following [PR](https://github.com/postlight/reader/pull/271)
