### ISSUE TITLE
Mercury Reader Down?

### ISSUE THREAD

**Issue by Digisaurus** [postlight/parser#692]
## Expected Behavior
Clicking the Postlight (Mercury) Chrome Extension icon doesn't work.

## Current Behavior
Clicking on the icon does nothing.  
Hovering shows:  "Postlight Reader".

## Steps to Reproduce
Try clicking on the "rocketship icon".   Nada.

## Detailed Description
This extension has always worked flawlessly, now it's not working.
Tried in Chrome on multiple machines, does nothing when you click on the icon.

## Possible Solution
The ball's in your court...

**Comment by sprock3t** [comment]
Same issue starting today - reader button does nothing, updated browser, restarted chrome, restarted machine, tried a different machine (win11 dell laptop, win10 desktop, both fully updated).

**Comment by johnholdun** [comment]
Hi, there was a bug in the most recent version (published today) that somehow managed to make its way past our QA and Google's. We submitted an updated version with a fix to the Chrome store this morning which resolves the bug and will hopefully be reviewed and published very soon. Sorry for the inconvenience!

**Comment by sprock3t** [comment]
Fix worked for me - thanks!

**Comment by johnholdun** [comment]
:raised_hands:
